### ISSUE TITLE
Error starting the game.

### ISSUE THREAD

**Issue by MrVaga** [shantek/UltimateBingo#38]
I have tried several 1.20+ versions, all give some version of this error, when i try to start the game.
https://pastebin.com/pc3VGpLm
The only thing that happens is that the time changes.

**Comment by shantek** [comment]
@MrVaga have you manually modified the bingoitems.yml file?

Are you able to send through a copy of this file for me to review?

**Comment by shantek** [comment]
@MrVaga  I've added some initial checks when running /bingo gui to ensure the game has enough items in the list to work with. Please try this version and see if it returns errors for you when opening the GUI

https://github.com/shantek/UltimateBingo/releases/tag/v0.7.3

**Comment by shantek** [comment]
This issue should now be resolved.
