### ISSUE TITLE
keepInventory gamerule isn't respected on player death during bingo

### ISSUE THREAD

**Issue by mathmasterzach** [shantek/UltimateBingo#46]
The plugin wipes the player's inventory when they die during a bingo game, even if the keepInventory gamerule is set to true.

**Comment by shantek** [comment]
@mathmasterzach  Fixed this bug in [6336248](https://github.com/shantek/UltimateBingo/commit/6336248efe0b19a4ade83f78f691f5bc15547900). 

Please test [dev build 16](https://shantek.dev/job/UltimateBingo/16/) to confirm this fixes the issue for you.
